### ISSUE TITLE
Error: Unable to list Dynamo tables

### ISSUE THREAD

**Issue by yeldarby** [smallwins/begin-issues#10]
I created a new app and followed the instructions to start it locally. On `npm start` I get an error message:

```
(base) iUSB-C-You:begin-app yeldarb$ npm start

> begin-app@0.0.0 start /Users/yeldarb/Code/begin-app
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox

        app ⌁ shiny-456
     region ⌁ us-west-2
    profile ⌁ undefined
    version ⌁ 5.6.0

✓ Shared code and .arc copied into 2 Functions
{ SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at JsonParser.parse (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/json/parser.js:6:25)
    at Request.extractData (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/protocol/json.js:62:24)
    at Request.callListeners (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'Unexpected token < in JSON at position 0',
  code: 'SyntaxError',
  time: 2019-04-06T14:46:35.497Z,
  statusCode: 200,
  retryable: false,
  retryDelay: 48.62442101924523 }
/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Unable to list Dynamo tables
    at Response._tables (/Users/yeldarb/Code/begin-app/node_modules/@architect/architect/src/sandbox/db/create-table/_create-table.js:17:13)
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:685:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! begin-app@0.0.0 start: `NODE_ENV=testing ARC_LOCAL=1 npx sandbox`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the begin-app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yeldarb/.npm/_logs/2019-04-06T14_46_35_512Z-debug.log
```

**Comment by ryanblock** [comment]
Hmm, I'm unable to replicate. Do you have stuff in your ~/.aws/credentials file, or somewhere else? Normally `profile` would read `xxx` if that file is empty, I'm wondering what's up with the `undefined` in there.

Also, Node + npm + OS version?

**Comment by yeldarby** [comment]
Looks like I have an `~/.aws/credentials` file but it's empty:

```
(base) iUSB-C-You:~ yeldarb$ ls -lh ~/.aws
total 0
-rw-r--r--  1 yeldarb  staff     0B Dec  4  2017 credentials
```

Versions:
```
(base) iUSB-C-You:~ yeldarb$ node --version
v11.10.1
(base) iUSB-C-You:~ yeldarb$ npm --version
6.9.0
(base) iUSB-C-You:~ yeldarb$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Comment by ryanblock** [comment]
That’s likely the problem. Try deleting that file, it should work!

**Comment by yeldarby** [comment]
Doesn't seem to have done the trick:
```
(base) iUSB-C-You:begin-app yeldarb$ mv ~/.aws/credentials ~/.aws/credentials_old
(base) iUSB-C-You:begin-app yeldarb$ npm start

> begin-app@0.0.0 start /Users/yeldarb/Code/begin-app
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox

        app ⌁ shiny-456
     region ⌁ us-west-2
    profile ⌁ undefined
    version ⌁ 5.6.0

✓ Shared code and .arc copied into 2 Functions
{ SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at JsonParser.parse (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/json/parser.js:6:25)
    at Request.extractData (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/protocol/json.js:62:24)
    at Request.callListeners (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'Unexpected token < in JSON at position 0',
  code: 'SyntaxError',
  time: 2019-04-07T14:44:54.963Z,
  statusCode: 200,
  retryable: false,
  retryDelay: 48.68741569054072 }
/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Unable to list Dynamo tables
    at Response._tables (/Users/yeldarb/Code/begin-app/node_modules/@architect/architect/src/sandbox/db/create-table/_create-table.js:17:13)
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/yeldarb/Code/begin-app/node_modules/aws-sdk/lib/request.js:685:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! begin-app@0.0.0 start: `NODE_ENV=testing ARC_LOCAL=1 npx sandbox`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the begin-app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yeldarb/.npm/_logs/2019-04-07T14_44_54_978Z-debug.log
(base) iUSB-C-You:begin-app yeldarb$ ls ~/.aws
credentials_old
```

**Comment by ryanblock** [comment]
Hmm, that's weird. I can't repro, and I've never seen this specific issue before. Node + npm + OS version?

A couple of ideas:
- rm -rf your root `node_modules` and do another `npm i`, then `npm start`
- Instead of `npm start`, try `npx sandbox` and see if that helps
- Perhaps try stubbing something into your local credentials file? (This one's a reach...)

**Comment by ryanblock** [comment]
Just following up, any luck?

**Comment by yeldarby** [comment]
Been on the road the last couple of days — will try again when I get home

**Comment by ryanblock** [comment]
No worries! Just wanted to make sure we didn't leave you hanging. I haven't been able to reproduce, so any repro vectors would be great. Thanks!

**Comment by yeldarby** [comment]
Weird, I tried `npm start` again and it worked this time!

I have rebooted and updated Mac OS since then. Not sure if that had anything to do with it. Maybe my `PATH` was screwed up previously?

**Comment by ryanblock** [comment]
Weird, no idea! Glad it's working though, seen a lot of issues, but never seen that one before – would fit the bill that it was potentially ephemeral.

**Comment by shoverian** [comment]
If anyone else is finds themselves facing a similar issue, make sure you don't have another instance running already.

I shut down an old, Begin terminal session, and didn't realize the server was still running in the background.
