### ISSUE TITLE
[begin-functions-app] Server on localhost crashes on requests

### ISSUE THREAD

**Issue by kmelve** [smallwins/begin-issues#4]
**Expected behavior**
The local “server” should return a response, and not crash.

**Description of bug**
```
~/Sites/begin-functions-app master*
❯ npm start

> begin-functions-app@1.0.0 start /Users/knutmelvaer/Sites/begin-functions-app
> NODE_ENV=testing npx sandbox


        ARC_APP_NAME test-app
          AWS_REGION us-west-2
         AWS_PROFILE xxx

                Node 9.11.1
                 npm 6.0.1
                .arc 3.2.18

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index

 ✓ Started HTTP "server" @  http://localhost:3333
{ ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Requested resource not found',
  code: 'ResourceNotFoundException',
  time: 2018-08-10T04:41:14.014Z,
  requestId: '<redacted>',
  statusCode: 400,
  retryable: false,
  retryDelay: 32.464603033333404 }
/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/knutmelvaer/Sites/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! begin-functions-app@1.0.0 start: `NODE_ENV=testing npx sandbox`
```

**Steps to reproduce**
1. Deleted node_modules
2. Updated all dependencies to the latest version
3. Run `npx hydrate`
4. Run `npm start`
5. Make a GET request to `localhost:3333`

**Desktop**
 - OS: macOS[e.g. macOS]
 - node/npm: v9.11.1 / 6.0.1

**Comment by ryanblock** [comment]
Hmm, @brianleroux may know more immediately what's up here – I'll have to troubleshoot a bit.

Did this randomly start happening? Did something change? (If so, any idea as to what?)

What happens if you change that to node 8.11? That is the runtime in Lambdaland, so you'd probably want that to match anyway.

**Comment by ryanblock** [comment]
Oh, and quick thing to try: looking at your `package.json` in your repo, you may want to do an `npm update` (specifically to freshen up `arc-workflows`, jic).

**Comment by kmelve** [comment]
Before the updates to the arc-dependencies, I didn't get it running at all, so this is in fact one step further 😄. But I've never got the server to return a response.

```
{
  "name": "begin-functions-app",
  "version": "1.0.0",
  "description": "Begin app",
  "scripts": {
    "lint": "eslint src --ignore-pattern node_modules --fix",
    "test": "NODE_ENV=testing tape test/*-test.js | tap-spec",
    "start": "NODE_ENV=testing npx sandbox"
  },
  "dependencies": {
    "@architect/workflows": "^3.2.18",
    "@begin-functions/data": "^1.0.4",
    "eslint": "^5.3.0",
    "tap-spec": "^5.0.0",
    "tape": "^4.9.1",
    "tiny-json-http": "^7.0.0"
  },
  "devDependencies": {
    "aws-sdk": "^2.290.0"
  }
}
```
All dependencies should be up to date.

I tried to run `npm start` on node 8.11. Same result. If I try to run `npx hydrate` on node 8/npm 5.6, I get this 

```
~/Sites/begin-functions-app master*
❯ nvm use 8
Now using node v8.11.3 (npm v5.6.0)

~/Sites/begin-functions-app master*
❯ npm i
npm WARN begin-functions-app@1.0.0 No repository field.
npm WARN begin-functions-app@1.0.0 No license field.

up to date in 1.265s

~/Sites/begin-functions-app master*
❯ npx hydrate
Error invalid npm version; must be 6 or higher
```

**Comment by kmelve** [comment]
1. Used `nvm` to switch to node 8 (which comes with npm 5.6 out of the box)
2. Upgraded npm to 6.3.0 with `npm i -g npm`
3. `npx hydrate` run successfully
4. Run `npm install` in `/get-index` just to make sure
5. Run `npm start` and curled `localhost:3333` with the same result

(Thinking you should have a section on how to work with multiple node-environment in the docs?)

**Comment by ryanblock** [comment]
Hmm, very sorry about that. Very frustrating, haven't seen this before.

Try one more thing, if you'd please?  In `package.json`, try changing `start` to `"NODE_ENV=testing ARC_LOCAL=1 npx sandbox"`

Removing `ARC_LOCAL` didn't replicate the problem on my side, so I'm shooting in the dark here, but 🤞🏻

**Comment by kmelve** [comment]
(I thought ARC_LOCAL=1 was something I did the last time we troubleshot this, but putting it in again didn't help either)

Hey, making dev software that should run on all the weird environments isn't easy. Just give me a ping when you're ready to look at this again 🙌

**Comment by brianleroux** [comment]
Super weird! Just woke up and taking a look rn.

**Comment by brianleroux** [comment]
@kmelve can you delete `node_modules` and run:

```bash
npm i
npx hydrate
unset AWS_PROFILE
npm start
```

And lmk if it still happens?

**Comment by kmelve** [comment]
Same error 🙃

**Comment by brianleroux** [comment]
oh! I have another theory! can you try `AWS_REGION=us-west-1 npm start`

**Comment by kmelve** [comment]
Success! 

```
~/Sites/begin-functions-app master* 12s
❯ AWS_REGION=us-west-1 npm start

> begin-functions-app@1.0.0 start /Users/knutmelvaer/Sites/begin-functions-app
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox


        ARC_APP_NAME test-app
          AWS_REGION us-west-1
         AWS_PROFILE xxx

                Node 9.11.1
                 npm 6.0.1
                .arc 3.2.18

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index

 ✓ Started HTTP "server" @  http://localhost:3333
{
  "method": "get",
  "path": "/",
  "headers": {
    "host": "localhost:3333",
    "user-agent": "curl/7.54.0",
    "accept": "*/*"
  },
  "query": {},
  "body": {},
  "params": {},
  "_idx": "<redacted>",
  "_secret": "<redacted>",
  "csrf": "<redacted>",
  "session": {}
}
```

Do you only operate in the us-west region? That can potentially be an issue with regards to GDPR and so on.

**Comment by ryanblock** [comment]
These values are just stubs to get the local environment working; afaik they don't necessarily correspond to reality for Begin users.

**Comment by brianleroux** [comment]
omg that was it! I'll def get a patch in for this case. we should have a default. 

@kmelve thx so much for helping us find/triage/fix this 🙏 

As Ryan said this is only local to your machine in memory fake-out. Begin pro tier accounts will support all the same regions AWS does and for now the free tier apps are from an end user perspective edge optimized CDN distributions (but I can see us allowing region selection in the future). 

> I'll keep this issue open while I patch arc-repos/arc-functions for this case!

**Comment by brianleroux** [comment]
This should be fixed using the latest versions of `architect/functions` (in your lambda functions) and `architect/workflows` (in the project root). Thx again for helping us w this!
