### ISSUE TITLE
Local development server exits with "UnknownError: 404"

### ISSUE THREAD

**Issue by impressiver** [smallwins/begin-issues#6]
**Expected behavior**
Following instructions for quickstart and local development, I should be able to run `npm start` and load the index route at `http://localhost:3333`.

**Description of bug**
Running `npm start` seems to bootstrap the local dev server without error:
```
$ npm start

> begin-functions-app@1.0.1 start /Users/ian/src/git/impressiver/begin-functions-app
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox


        ARC_APP_NAME dictum-n8q
          AWS_REGION us-west-2
         AWS_PROFILE xxx

                Node 8.11.3
                 npm 6.3.0
                .arc 3.2.19

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index
 get /echo/:str ........................ get-echo-000str

 ✓ Started HTTP "server" @  http://localhost:3333
```

But as soon as I load `http://localhost:3333` in a browser, the process exits w/ the following stack trace:
```
{ UnknownError: 404
    at Request.extractError (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: '404',
  code: 'UnknownError',
  statusCode: 404,
  time: 2018-08-11T21:04:49.771Z,
  requestId: undefined,
  retryable: false,
  retryDelay: 28.650255248456446 }
/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

UnknownError: 404
    at Request.extractError (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! begin-functions-app@1.0.1 start: `NODE_ENV=testing ARC_LOCAL=1 npx sandbox`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the begin-functions-app@1.0.1 start script.
```

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Follow step-by-step directions for local setup:
  1. **Note:** I used `git://` instead of `https://`
  2. `git clone git://github.com/impressiver/begin-functions-app.git`
  3. `cd begin-functions-app`
  4. `npm install`
  5. `npx hydrate`
  6. `npm start`
2. Open browser to `http://localhost:3333`, Chrome shows "This site can't be reached"
3. Console shows the process has exited, dumping the above stack trace

**Desktop**
 - OS: macOS 10.14 Beta (18A353d)
 - Browser: Chrome 68.0.3440.106 (Official Build) (64-bit)
 - Node: v8.11.3
 - npm: 6.3.0

**Additional context or notes**
I use `nvm` to install/use different versions of node.
I have `aws-sdk` installed globally and configured w/ my aws credentials, if that matters.

**Comment by ryanblock** [comment]
Full issue from before for reference:

**Expected behavior**
Following instructions for quickstart and local development, I should be able to run `npm start` and load the index route at `http://localhost:3333`.


**Description of bug**
Running `npm start` seems to bootstrap the local dev server without error:
```
$ npm start

> begin-functions-app@1.0.1 start /Users/ian/src/git/impressiver/begin-functions-app
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox


        ARC_APP_NAME dictum-n8q
          AWS_REGION us-west-2
         AWS_PROFILE xxx

                Node 8.11.3
                 npm 6.3.0
                .arc 3.2.19

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index
 get /echo/:str ........................ get-echo-000str

 ✓ Started HTTP "server" @  http://localhost:3333
```

But as soon as I load `http://localhost:3333` in a browser, the process exits w/ the following stack trace:
```
{ UnknownError: 404
    at Request.extractError (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: '404',
  code: 'UnknownError',
  statusCode: 404,
  time: 2018-08-11T21:04:49.771Z,
  requestId: undefined,
  retryable: false,
  retryDelay: 28.650255248456446 }
/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

UnknownError: 404
    at Request.extractError (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/ian/src/git/impressiver/begin-functions-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! begin-functions-app@1.0.1 start: `NODE_ENV=testing ARC_LOCAL=1 npx sandbox`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the begin-functions-app@1.0.1 start script.
```


**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Follow step-by-step directions for local setup:
  1. **Note:** I used `git://` instead of `https://`
  2. `git clone git://github.com/impressiver/begin-functions-app.git`
  3. `cd begin-functions-app`
  4. `npm install`
  5. `npx hydrate`
  6. `npm start`
2. Open browser to `http://localhost:3333`, Chrome shows "This site can't be reached"
3. Console shows the process has exited, dumping the above stack trace


**Desktop**
 - OS: macOS 10.14 Beta (18A353d)
 - Browser: Chrome 68.0.3440.106 (Official Build) (64-bit)
 - Node: v8.11.3
 - npm: 6.3.0


**Additional context or notes**
I use `nvm` to install/use different versions of node.
I have `aws-sdk` installed globally and configured w/ my aws credentials, if that matters.

**Comment by ryanblock** [comment]
Thanks, this is a very well reported issue.

The things I'd normally want to look into (such as our recent update addressing #4) don't seem to apply here.

Since you mentioned you've got local AWS creds, can we try something to see if it's potentially related / conflicting?

I'd have you just do a simple `mv ~/.aws/credentials ~/.aws/credentials-hold` and try that repro flow again and see what happens. (Move it back to the original filename when you're done with that, of course.)

**Comment by brianleroux** [comment]
also: can you try downgrading npm `npm i npm@6.1.0 -g` and re-running `npm i && npx hydrate && npm start`

**Comment by impressiver** [comment]
No luck pinning npm 6.1.0 or removing aws credentials. What version of node are you guys running?

```
$ mv ~/.aws/credentials{,.bak}
$ rm -rf node_modules/
$ npm i npm@6.1.0 -g
...
+ npm@6.1.0
updated 1 package in 15.115s
```
```
$ npm i

> leveldown@4.0.1 install /Users/ian/src/git/impressiver/begin-functions-app/node_modules/leveldown
> prebuild-install || node-gyp rebuild

npm WARN begin-functions-app@1.0.1 No repository field.
npm WARN begin-functions-app@1.0.1 No license field.

added 382 packages from 348 contributors and audited 777 packages in 10.818s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```
```
$ npx hydrate

        ARC_APP_NAME dictum-n8q
          AWS_REGION us-west-2
         AWS_PROFILE xxx

                Node 8.11.3
                 npm 6.1.0
                .arc 3.2.19

✓ Success 1646ms
```
```
$ npm start

> begin-functions-app@1.0.1 start /Users/ian/src/git/impressiver/begin-functions-app
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox


        ARC_APP_NAME dictum-n8q
          AWS_REGION us-west-2
         AWS_PROFILE xxx

                Node 8.11.3
                 npm 6.1.0
                .arc 3.2.19

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index
 get /echo/:str ........................ get-echo-000str

 ✓ Started HTTP "server" @  http://localhost:3333
{ UnknownError: 404
... same stack trace and exit ...
```

AWS cli shows no default credentials loaded:
```
$ aws configure
AWS Access Key ID [None]:
AWS Secret Access Key [None]:
Default region name [us-east-1]:
Default output format [json]:
$ ls ~/.aws/
aws-keychain.list  config  credentials.bak  keys
```

**Comment by impressiver** [comment]
I’m looking into the `architect` docs, they expect node `8.10.x` to match aws. Let me try that, I’ve seen weirder than this on minor version mismatches.

**Comment by impressiver** [comment]
No diff...
```
$ npm start

> begin-functions-app@1.0.1 start /Users/ian/src/git/impressiver/begin-functions-app
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox


        ARC_APP_NAME dictum-n8q
          AWS_REGION us-west-2
         AWS_PROFILE xxx

                Node 8.10.0
                 npm 6.1.0
                .arc 3.2.19

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index
 get /echo/:str ........................ get-echo-000str

 ✓ Started HTTP "server" @  http://localhost:3333
{ UnknownError: 404
...
```

**Comment by brianleroux** [comment]
Super weird, what is your `NODE_ENV`?

**Comment by brianleroux** [comment]
Sorry / can see its in the output. Long week! 😴 Just cloned your repo and gave it a go / here's my output:

```
#! npm i && npx hydrate && npm start

> leveldown@4.0.1 install /Users/brianleroux/Desktop/impressiver/node_modules/leveldown
> prebuild-install || node-gyp rebuild

npm WARN begin-functions-app@1.0.2 No repository field.
npm WARN begin-functions-app@1.0.2 No license field.

added 382 packages from 348 contributors and audited 777 packages in 15.136s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

        ARC_APP_NAME dictum-n8q
          AWS_REGION us-east-1
         AWS_PROFILE smallwins

                Node 8.11.2
                 npm 6.1.0
                .arc 3.2.19

✓ Success 5831ms

> begin-functions-app@1.0.2 start /Users/brianleroux/Desktop/impressiver
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox


        ARC_APP_NAME dictum-n8q
          AWS_REGION us-east-1
         AWS_PROFILE smallwins

                Node 8.11.2
                 npm 6.1.0
                .arc 3.2.19

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index
 get /echo/:str ........................ get-echo-000str

 ✓ Started HTTP "server" @  http://localhost:3333
```

I have an `AWS_PROFILE` set here. So I tried again without it:

```
#! unset AWS_PROFILE && npm start

> begin-functions-app@1.0.2 start /Users/brianleroux/Desktop/impressiver
> NODE_ENV=testing ARC_LOCAL=1 npx sandbox


        ARC_APP_NAME dictum-n8q
          AWS_REGION us-east-1
         AWS_PROFILE xxx

                Node 8.11.2
                 npm 6.1.0
                .arc 3.2.19

✓ @tables created in local database
✓ src/shared copied to lambda node_modules/@architect/shared
✓ .arc copied to lambda node_modules/@architect/shared/.arc
✓ @events pub/sub ready on local event bus

 @html
 get / ................................. get-index
 get /echo/:str ........................ get-echo-000str

 ✓ Started HTTP "server" @  http://localhost:3333
```

Which also worked! Hate to be superstitious but maybe try installing Node 8.11.2 and npm 6.1.0 ? Also what version of the `aws-sdk` do you have?

**Comment by brianleroux** [comment]
closing for inactivity but pls feel free to reopen
